Connected to Python 3.12.2

In [1]:
import numpy as np

# Create a NumPy arrayddddff
arr = np.array([[1, 2, 3],
                [4, 0, 6],
                [7, 8, 9]])

# Specify the row index you want to check (e.g., row index 1)
row_index = 1

# Check if the specified row contains no zeros
contains_no_zeros = np.all(arr[row_index] != 0)

print(f"Row {row_index} contains no zeros: {contains_no_zeros}")


Row 1 contains no zeros: False


In [2]:
np.all(arr[row_index] != 0)

False

In [3]:
np.all(arr[row_index])

False

In [4]:
np.all(arr[0])

True

In [5]:
np.all(arr[1])

False

In [6]:
np.delete(1)

TypeError: delete() missing 1 required positional argument: 'obj'

In [7]:
np.delete(arr, 1)

array([1, 3, 4, 0, 6, 7, 8, 9])

In [8]:
arr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [9]:
np.delete(arr, 1, axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [10]:
arr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [11]:
empty_row = np.array([[0, 0, 0]])

In [12]:
new_arr = np.append(arr, empty_row, axis=0)


In [13]:
new_arr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9],
       [0, 0, 0]])

In [14]:
new_arr = np.vstack((arr, empty_row))


In [15]:
new_arr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9],
       [0, 0, 0]])

In [16]:
arr+empty_row

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [17]:
arr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [18]:
empty_line = np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 0)

In [ ]:
import numpy

In [ ]:
import numpy as np

In [ ]:
np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])

In [ ]:
import timeit

In [ ]:
timeit.timeit(lambda:np.zeros((5,1))


SyntaxError: incomplete input (<ipython-input-5-deb6bfc7abb5>, line 1)

In [ ]:
timeit.timeit(lambda:np.zeros((5,1)))

0.3166067390002354

In [ ]:
timeit.timeit(lambda:np.zeros((1,5)))

0.30951497000023664

In [ ]:
timeit.timeit(lambda:np.zeros((10,20)))

0.5496872980002081

In [ ]:
timeit.timeit(lambda:np.zeros((20,10)))

0.5886326350000672

In [ ]:
np.zeros((20,10)

SyntaxError: incomplete input (<ipython-input-10-a66213b69cc2>, line 1)

In [ ]:
np.zeros((20,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
cubes1 = np.zeros((20,10)

SyntaxError: incomplete input (<ipython-input-12-e8266c20c9fa>, line 1)

In [ ]:
cubes1 = np.zeros((20,10))

In [ ]:
cubes1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
cubes2 = np.zeros((10,20))

In [ ]:
cubes2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [ ]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

# Remove the 2nd column (index 1)
new_arr = np.delete(arr, 1, axis=1)

print(new_arr)

[[1 3]
 [4 6]
 [7 9]]


In [ ]:
%timeit np.delete(cubes1,19,axis=0)

4.16 µs ± 25.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
%timeit np.delete(cubes2,19,axis=1)

4.18 µs ± 23.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
np.delete(cubes2,19,axis=0)

IndexError: index 19 is out of bounds for axis 0 with size 10

In [ ]:
empty_line1 = np.array((1,10))

In [ ]:
empty_line2 = np.array((10,1))

In [ ]:
empty_line2

array([10,  1])

In [ ]:
empty_line1 = np.zeros((1,10))

In [ ]:
empty_line2 = np.zeros((10,1))

In [ ]:
empty_line1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
empty_line2

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
np.hstack((empty_line1,cubes1))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 20

In [ ]:
np.vstack((empty_line1,cubes1))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 

In [ ]:
np.vstack((empty_line1,cubes1)).ndims

AttributeError: 'numpy.ndarray' object has no attribute 'ndims'

In [ ]:
np.vstack((empty_line1,cubes1)).shape

(21, 10)

In [ ]:
np.hstack((empty_line2,cubes2))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.,

In [ ]:
np.hstack((empty_line2,cubes2)).shape

(10, 21)

In [ ]:
%timeit np.vstack((empty_line1,cubes1))

2.78 µs ± 92.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
%timeit np.hstack((empty_line2,cubes2))

2.82 µs ± 18.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
